# Generated by Django 4.2.2 on 2023-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=50)),
                ('recording_time', models.DateTimeField()),
                ('connection_time', models.DateTimeField(auto_now_add=True)),
                ('device_location', models.CharField(max_length=100)),
            ],
        ),
    ]
