# Generated by Django 4.2.2 on 2023-07-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate_processor', '0003_remove_licenseplate_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseplate',
            name='car_color',
        ),
    ]
